name: duo_rating_dialog
description: An extended version of the rating_dialog package. Allows user to
  rate two Star Rating bars.
version: 0.1.1
homepage: https://github.com/vipinkashyap/duo_rating_dialog

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter: null
