name: zendesk_unified
description: "Flutter plugin for interacting with Zendesk's Unified SDK."
version: 0.0.1
publish_to: none
environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  zendesk_unified_platform_interface:
    path: ../zendesk_unified_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mrowl.zendesk_unified
        pluginClass: ZendeskUnifiedPlugin
      ios:
        pluginClass: ZendeskUnifiedPlugin
